### PR TITLE
Organize the playbook's structure

### PR DESCRIPTION
**Pull request by sales**
Organizing our Playbook 🎉 

@vhaidamus and I are working on [this document](https://docs.google.com/document/d/1NyJkNMloT1RD7jyrpqRk4-91UaVsVYVEQKq-H1-ZbMg/edit#heading=h.87vt63c1gjlq) to organize and structure our playbook.

##### Done in this PR
- Change our file structure
- Change priorities
- Reorganize and break some sections into more

##### Known issues

- Just found a bug that the children page `What's Startaê?` is remaining opened all the time. I'll fix that in the next PR

##### Demo

image

Please review @startae/frontend-team

### CODE REVIEW

**Comment by tmeloliveira** [comment]
Just added a short description to the **_Tools_** index page: https://github.com/startae/playbook/pull/5/commits/149da6592a0ee058f4d877ce5e1cf8168a5e534d

LGTM! :shipit:

**Comment by renatocarvalho** [comment]
👀

**Comment by renatocarvalho** [comment]
I added a few more tweaks. The first one was bothering me a lot 😬 

- Removed “What’s Startaê” (Also moved the content about Startaê to the root of the Playbook, it's not perfect, but better than having "What's Startaê") 😌 
- Rename “The Schedule” to “Working hours“
- Add embed video on the content of the Wired section

**Comment by renatocarvalho** [comment]
I tested here the new structure and one thing I noticed it's a bit strange is that when I open the `Tools` section and go to some sub-section like `Development`. The section `Development` outside `Tools` will also open.

nov-22-2016 12-12-55

**Comment by sales** [comment]
👀

**Comment by sales** [comment]
Fixed 😌

**Comment by renatocarvalho** [comment]
🎉

**Pull request merged**
