### PR TITLE
Update favicon

### PR DESCRIPTION
**Pull request by sales**
##### Done in this PR
- Update `favicon` and `og_image` following our site pattern

**Demo**
image

Please review @startae/frontend-team

### CODE REVIEW

**Comment by kandebonfim** [comment]
wow, very important thing here! haha

**Comment by kandebonfim** [comment]
👀

**Comment by kandebonfim** [comment]
We should use an `1200x630px` image as recommended by facebook [here](https://developers.facebook.com/docs/sharing/best-practices).

It's my bad I have to do this change in our main site too. :/

**Comment by kandebonfim** [comment]
LGTM. Last review, @sales?

**Comment by sales** [comment]
Nice! ✨ 🚀

**Pull request merged**
