### PR TITLE
Add ‘How things work here’

### PR DESCRIPTION
**Pull request by kandebonfim**
##### Known issues
- Some of the section are still in portuguese. We need to translate them ASAP.
##### Demo

captura de tela 2016-10-28 as 12 50 38

Please review @startae/frontend-team

### CODE REVIEW

**Comment by renatocarvalho** [comment]
@kandebonfim Awesome! I'll take a look in a few minutes.

**Comment by sales** [comment]
@kandebonfim, I'll help translating

**Comment by sales** [comment]
Pomodoro - translated ✅

**Comment by tmeloliveira** [comment]
OKR - translated ✅ 
Index page - reviwed ✅

**Comment by tmeloliveira** [comment]
Wired - translated ✅

**Comment by renatocarvalho** [comment]
Beautiful guys! Thanks for the help. I'll merge like this and we can improve as we go. 👊

**Pull request merged**
