### PR TITLE
Design tweaks

### PR DESCRIPTION
**Pull request by kandebonfim**
#### Sidebar
playbook__nav--animation

#### Sidebar medium/small screens
playbook_nav

### CODE REVIEW

**Comment by sales** [comment]
@kandebonfim 👓

**Comment by sales** [comment]
Nice work! 👍 👯 

Just a few adjustments:

image

There's a visible scroll in the sidebar, even when it's unnecessary:

**Comment by kandebonfim** [comment]
@sales I already fixed the scrolling issue but I'm not sure of what is happening with this weird border You mentioned. It only appears for me while sidebar is opening/closing. Can you help me with this?

**Comment by sales** [comment]
A few adjustments in mobile:

image

What about reducing this space in the list?

image

When I tested simulating an iPhone 5, there was no way to close the menu:

**Comment by sales** [comment]
Of course, let's pair.

**Comment by kandebonfim** [comment]
@sales as we talked, I'll let the mobile adjustments for the next PR. The first two bugs you mentioned is already fixed!

**Pull request merged**
