### PR TITLE
Add tools, flow and template for tasks

### PR DESCRIPTION
**Pull request by sales**
##### Done in this PR
- Add `tools` page
- Add `Flow` and the guide to write tasks

##### Demo

image

Please review @startae/frontend-team

### CODE REVIEW

**Comment by renatocarvalho** [comment]
What about creating another section on the menu called "Tools"? Outside the section "How things work here". Then the subsection would be "Flow" with all these details?

**Comment by sales** [comment]
@renatocarvalho, I thought about that, but the point is that we already have a section called `Tools` in Development and Design sections. 🤔

**Comment by renatocarvalho** [comment]
🤔 Good catch. We'll probably need to rethink the Playbook structure.

Well, what about changing the "Tools" to "Project Management" for now?

**Comment by sales** [comment]
Nice! Done @renatocarvalho

**Pull request merged**
